### ISSUE TITLE
Support `glob` 8.x

### ISSUE THREAD

**Issue by allanlewis** [ahmadnassri/node-glob-promise#157]
The `glob` project released 8.x. The [only reported change](https://github.com/isaacs/node-glob/blob/a8a3682527640e5356e0448330c5955081efa85f/changelog.md) is:

> Only support node v12 and higher

So there isn't an obvious reason why this project couldn't work with `glob` 8.x as a peer dependency.

**Comment by ahmadnassri** [comment]
now updated to [`v5.0.0`](https://github.com/ahmadnassri/node-glob-promise/releases/tag/v5.0.0) with `glob@v8`
