### ISSUE TITLE
Package still maintained?

### ISSUE THREAD

**Issue by spacedawwwg** [ahmadnassri/node-glob-promise#167]
I'm just wondering if this package is still maintained, @ahmadnassri?

**Comment by ahmadnassri** [comment]
indeed it is, now updated to [`v5.0.0`](https://github.com/ahmadnassri/node-glob-promise/releases/tag/v5.0.0) with `glob@v8`

**Comment by spacedawwwg** [comment]
@ahmadnassri thank you!

**Comment by cossssmin** [comment]
@ahmadnassri I'm seeing it failing in CI on Node 14, looks like the `glob` dependency can't be found:

https://github.com/maizzle/framework/runs/7615135140?check_suite_focus=true
