### ISSUE TITLE
`@types/glob` should be defined as devDependency

### ISSUE THREAD

**Issue by vojty** [ahmadnassri/node-glob-promise#203]
I believe `@types/glob` should be defined as dev dependency.

I have installed `glob@10.0.0` which ships its own type definitions but they are overridden by `@types/glob` which are required in this package.

**Comment by thanaParis** [comment]
bumping this! @types/glob being a direct dependency instead of a dev dependency causes any build referencing glob@>=9.0.0 to break, as glob starting supporting native typescript natively in v9.0.0 and is no longer compatible with (or needs) @types/glob
